// import BackgroundImage from "@/src/components/home/BackgroundImage";
// import ImageGallery from "@/src/components/home/ImageGrid";
// import { createClient } from "@/src/lib/supabase/server";
// import HorizontalImageScroller from "@/src/components/landing/HorizontalImageScroller";
// import Image from "next/image";

const sampleImages = [
  {
    src: "https://nvbssjoomsozojofygor.supabase.co/storage/v1/object/public/images/ai_apps/Ai_girlfriend/Ai-girlfriend-thumbnail-small.mp4",
    alt: "A snow-covered mountain range under a cloudy sky",
    width: 805,
    height: 1280,
    title: "AI Girlfriend",
    subtext: "Make your imaginary girlfriend do anything for you.",
  },
  {
    src: "https://nvbssjoomsozojofygor.supabase.co/storage/v1/object/public/images/ai_apps/Dance_transfer/Dance-tranfer-thumbnail-small.mp4",
    alt: "Close-up of a colorful bird with a vibrant beak",
    width: 805,
    height: 1280,
    title: "WAN 2.2 Dance transfer",
    subtext: "Transfer any moment to any picture you want",
  },
  {
    src: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/516c8d4e-9fa0-46fa-a60a-a20826dadadf/transcode=true,original=true,quality=90/106778230.webm",
    alt: "An underwater shot of a sea turtle swimming",
    width: 1280,
    height: 705,
    title: "dnds gdaisogn asof",
    subtext: "sdmf asionfasiofnsa ifhnasjfnsaiofhj",
  },
  {
    src: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a237fca1-59c1-4615-acfc-2d76a419eb23/original=true,quality=90/ComfyUI_00002_mnkhu_1755432615.jpeg",
    alt: "A desert landscape with a person standing on a rock formation",
    width: 1600,
    height: 1067,
  },
  {
    src: "https://nvbssjoomsozojofygor.supabase.co/storage/v1/object/public/images/ai_apps/4k_upscale/4k_video_cover.mp4",
    alt: "A person snorkeling in crystal clear water",
    width: 1024,
    height: 1024,
  },
];

// const Page = async () => {
//   const supabase = await createClient();

//   const { data: images, error } = await supabase.rpc("get_example_generations", {
//     p_limit: 10,
//     p_showcase_for: "advance_generate",
//   });

//   if (error) {
//     console.error("Error fetching random images:", error);
//     return <p className="text-center text-white">Failed to load images. Please try again later.</p>;
//   }

//   return (
//     <section className="relative mt-12">
//       <HorizontalImageScroller images={sampleImages} galleryHeight={450} />

//       <div className="flex flex-col gap-12">
//         {/* --- First Section (Video background) --- */}
//         <div className="relative">
//           <div
//             className="pointer-events-none relative w-full overflow-hidden"
//             style={{ height: "80vh" }}
//           >
//             <video
//               src="https://nvbssjoomsozojofygor.supabase.co/storage/v1/object/public/images/showcase/sora2/anime_girl_in_real_small.mp4"
//               className="h-full w-full object-cover object-center"
//               autoPlay
//               muted
//               loop
//               playsInline
//             />
//             <div className="absolute inset-0 bg-black/50" />
//             <div className="absolute inset-x-0 bottom-0 h-10 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,white,transparent)] sm:h-16" />
//             <div className="absolute inset-x-0 top-0 h-10 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,transparent,white)] sm:h-16" />
//           </div>

//           <div className="relative -mt-40 flex w-full flex-col items-center z-10 justify-center px-4 text-center sm:-mt-60 md:-mt-80">
//             <h1 className="font-satoshi text-3xl font-bold uppercase text-accent drop-shadow-lg sm:text-4xl md:text-5xl lg:text-6xl">
//               Generated by WAN 2.2
//             </h1>

//             <div className="mt-10 sm:mt-16">
//               <ImageGallery showMore columnCount={5} images={images} />
//             </div>
//           </div>
//         </div>

//         {/* --- Second Section (Image background) --- */}
//         <div className="relative">
//           <div
//             className="pointer-events-none relative w-full overflow-hidden"
//             style={{ height: "80vh" }}
//           >
//             <Image
//               src="https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/87d8030c-e995-41cb-801e-25a4583cf3cd/original=true,quality=90/ComfyUI_00002_shnxr_1755699523.jpeg"
//               fill
//               className="rounded-[2rem] object-cover"
//               alt="Cover image"
//             />
//             <div className="absolute inset-0 bg-black/50" />
//             <div className="absolute inset-x-0 bottom-0 h-10 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,white,transparent)] sm:h-16" />
//             <div className="absolute inset-x-0 top-0 h-10 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,transparent,white)] sm:h-16" />
//           </div>

//           <div className="relative -mt-40 flex w-full flex-col items-center justify-center px-4 text-center sm:-mt-60 md:-mt-80">
//             <h1 className="font-satoshi text-3xl font-bold uppercase text-accent drop-shadow-lg sm:text-4xl md:text-5xl lg:text-6xl">
//               Generated by WAN 2.2
//             </h1>

//             <div className="mt-10 sm:mt-16">
//               <ImageGallery showMore columnCount={5} images={images} />
//             </div>
//           </div>
//         </div>
//       </div>
//     </section>
//   );
// };

// export default Page;

import { ShowcaseClient } from "@/src/components/home/ShowcaseClient";
import HorizontalImageScroller from "@/src/components/landing/HorizontalImageScroller";
import { createClient } from "@/src/lib/supabase/server";

export const revalidate = 3600; // Revalidate every hour

const Page = async () => {
  const supabase = await createClient();

  const { data: models, error } = await supabase
    .from("showcaseimages")
    .select("generated_by")
    .order("generated_by", { ascending: true });

  if (error || !models) {
    return <p className="text-center text-white">Could not load model data.</p>;
  }

  const uniqueModelNames = [
    ...new Set(models.map((m) => m.generated_by).filter((name): name is string => !!name)),
  ];

  return (
    <section className="relative mt-12">
      <HorizontalImageScroller images={sampleImages} galleryHeight={450} />
      <div className="flex flex-col gap-24">
        {uniqueModelNames.length > 0 && <ShowcaseClient models={uniqueModelNames} />}
      </div>
    </section>
  );
};

export default Page;
