// app/ShowcaseSection.tsx
"use client";

import Image from "next/image";

import { ModelShowcase } from "@/src/hooks/useShowcaseImages";

import ImageGallery from "./ImageGrid";

interface ShowcaseSectionProps {
  modelData: ModelShowcase;
}

export const ShowcaseSection = ({ modelData }: ShowcaseSectionProps) => {
  const { name, cover, images } = modelData ?? ({} as ModelShowcase);

  if (!cover || !images) {
    return null;
  }

  return (
    <section className="relative">
      <div
        className="pointer-events-none relative w-full overflow-hidden"
        style={{ height: "80vh" }}
      >
        {cover.isVideo ? (
          <video
            src={cover.mediaUrl}
            className="size-full object-cover object-center"
            autoPlay
            muted
            loop
            playsInline
          />
        ) : (
          // parent is relative so Image with `fill` works
          <Image
            src={cover.mediaUrl}
            fill
            className="object-cover"
            alt={`Cover image for ${name}`}
            priority
          />
        )}

        <div className="absolute inset-0 bg-black/60" />
        <div className="absolute inset-x-0 bottom-0 h-16 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,white,transparent)]" />
        <div className="absolute inset-x-0 top-0 h-16 bg-black backdrop-blur-lg [mask-image:linear-gradient(to_top,transparent,white)]" />
      </div>

      <div className="relative z-10 -mt-40 flex w-full flex-col items-center justify-center px-4 text-center sm:-mt-60 md:-mt-80">
        <h1 className="font-satoshi text-3xl font-bold uppercase text-accent drop-shadow-lg sm:text-4xl md:text-5xl lg:text-6xl">
          Generated by {name}
        </h1>

        <div className="mt-10 w-full sm:mt-16">
          <ImageGallery showMore columnCount={5} images={images} />
        </div>
      </div>
    </section>
  );
};
